### ISSUE TITLE
Panda-70M as the dataset

### ISSUE THREAD

**Issue by alfredplpl** [PKU-YuanGroup/Open-Sora-Plan#10]
Panda-70M is available right now.

https://snap-research.github.io/Panda-70M/

This contains 70M video-text pairs.
It seems useful for this project.
What do you think?

**Comment by cxh0519** [comment]
Thanks for your attention! We are downloading Panda-70M already for further investigation.

**Comment by alfredplpl** [comment]
Awesome.
