### ISSUE TITLE
What kind of and how many GPUs do you use to train and inference？

### ISSUE THREAD

**Issue by Pass-O-Guava** [PKU-YuanGroup/Open-Sora-Plan#157]

**Comment by LinB203** [comment]
For training a initial verision, we think maybe 128-256 A100 gpus to train 1 week. For inference, a 16G gpu is ok.

**Comment by Nuclear6** [comment]
The google/mt5-xxl model is so big, can a 16G GPU meet the requirements?

**Comment by zishen-ucap** [comment]
> For training a initial verision, we think maybe 128-256 A100 gpus to train 1 week. For inference, a 16G gpu is ok.

回答是3月了，估计是1.0版本，然后作者在技术报告中原话是这样的

> Due to the high computational complexity of 3D full attention, we must allocate a video across 2 GPUs for parallel processing when training with long-duration and high-resolution videos. We can control the number of GPUs used for a video sample by adjusting the batch size on a node. For example, with sp_size=8 and train_sp_batch_size=4, 2 GPUs are used for a single sample. We support sequence parallelism for both training and inference.
