### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by ChengHSUHSU** [PKU-YuanGroup/Open-Sora-Plan#170]
python examples/rec_video_vae.py --rec-path test_video.mp4 --video-path video.mp4 --resolution 512 --num-frames 1440 --sample-rate 1 --sample-fps 24 -
-device cuda --ckpt <Your ckpt>

the command is not workable in configuration

**Comment by qqingzheng** [comment]
I apologize that the inference command in the README has not been updated. Currently, we have optimized the inference code, and the parameters have changed. Please attach the '-h' parameter to view the new input parameters.

**Comment by 1030zero** [comment]
> 很抱歉 README 中的推理命令尚未更新。目前我们已经优化了推理代码，参数也发生了变化。请附加“-h”参数以查看新的输入参数。
How to view new input parameters？
