### ISSUE TITLE
Fine-tuning

### ISSUE THREAD

**Issue by COST-97** [PKU-YuanGroup/Open-Sora-Plan#191]
Hello:
     Very outstanding work!
     Can you provide a tutorial on fine-tuning based on the Open-Sora-Plan v1.0.0 model?
Thank you so much!

**Comment by LinB203** [comment]
In fact each stage is a fine-tuning of the previous stage, and you can observe the difference between stage 2 scripts and stage 1 to customize your fine-tuning scripts.

**Comment by LinB203** [comment]
Sorry, we fixed the training script.
See https://github.com/PKU-YuanGroup/Open-Sora-Plan/blob/main/scripts/text_condition/train_videoae_65x512x512.sh#L31
