### ISSUE TITLE
 cannot import name 'CombinedTimestepSizeEmbeddings'

### ISSUE THREAD

**Issue by huy708** [PKU-YuanGroup/Open-Sora-Plan#194]
File "D:\stable-diffusion\sora\Open-Sora-Plan\opensora\models\diffusion\latte\modules.py", line 14, in <module>
    from diffusers.models.embeddings import get_1d_sincos_pos_embed_from_grid, ImagePositionalEmbeddings, CaptionProjection, \
ImportError: cannot import name 'CombinedTimestepSizeEmbeddings' from 'diffusers.models.embeddings' (C:\Users\Admin\AppData\Roaming\Python\Python310\site-packages\diffusers\models\embeddings.py)

Can you help me fix this error?

**Comment by LinB203** [comment]
Since we updated the diffusers version, we added these within the code to adapt. Please check out our latest code.
https://github.com/PKU-YuanGroup/Open-Sora-Plan/blob/main/opensora/models/diffusion/latte/modules.py#L32
