### ISSUE TITLE
Is the data on hugging face complete?

### ISSUE THREAD

**Issue by Aus-Ge** [PKU-YuanGroup/Open-Sora-Plan#195]
dear developer, I noticed that the video data you provided on the hugging face platform -- LanguageBind/Open-Sora-Plan-v1.0.0, contain 1 mixkit package, 00-05 pexels package, and 00-19 pixabay package. Are these the whole data uploaded? (especially the pixabay data, I want to ensure if there exist any more increments)

**Comment by LinB203** [comment]
Complete now.
