### ISSUE TITLE
How to load pretrained model?

### ISSUE THREAD

**Issue by howardgriffin** [PKU-YuanGroup/Open-Sora-Plan#196]
I want to finetune t2v model on my own dataset.
However, when I used the pretained model `'65x512x512/diffusion_pytorch_model.safetensors'` as the pretrained model, the error` '_pickle.UnpicklingError: invalid load key, '\xbb'.'` occured.
Any suggestions?

**Comment by LinB203** [comment]
Sorry, we fixed the training script. In fact each stage is a fine-tuning of the previous stage, and you can observe the difference between stage 2 scripts and stage 1 to customize your fine-tuning scripts.
See https://github.com/PKU-YuanGroup/Open-Sora-Plan/blob/main/scripts/text_condition/train_videoae_65x512x512.sh#L31

**Comment by howardgriffin** [comment]
In face, I can not get the model you mentioned [here](https://github.com/PKU-YuanGroup/Open-Sora-Plan/blob/main/scripts/text_condition/train_videoae_65x512x512.sh#L31), so I use this [pretrained model](https://huggingface.co/LanguageBind/Open-Sora-Plan-v1.0.0/blob/main/65x512x512/diffusion_pytorch_model.safetensors) to finetune(just like `--pretrained='LanguageBind/Open-Sora-Plan-v1.0.0/65x512x512/diffusion_pytorch_model.safetensors' `in my training script), but still reported this error  `'_pickle.UnpicklingError: invalid load key, '\xbb'.`

**Comment by LinB203** [comment]
Sorry again. We fixed that.
