### ISSUE TITLE
the open-sora can Image condition?

### ISSUE THREAD

**Issue by ChengHSUHSU** [PKU-YuanGroup/Open-Sora-Plan#219]
In future, the project will support  Image condition, even video condition??

**Comment by LiuhanChen-github** [comment]
yes, we will add control as soon as the training of the base T2V model is finished.

**Comment by qiuhaining** [comment]
> yes, we will add control as soon as the training of the base T2V model is finished.

controlnet or GLIGEN? like this https://zhuanlan.zhihu.com/p/684356955

**Comment by Xelawk** [comment]
Any more news?

**Comment by pramishp** [comment]
Any updates on this ?
