### ISSUE TITLE
How to resume Video Diffusion Transformer

### ISSUE THREAD

**Issue by alfredplpl** [PKU-YuanGroup/Open-Sora-Plan#231]
Great work!
I move your work.

I would like to finetune your Video Diffusion Transformer.
However, I could not find the pretrained model. (--pretrained t2v.pt)
So, I could not finetune it.

```bash
export WANDB_KEY=""
export ENTITY=""
export PROJECT="animesora"
accelerate launch \
    --config_file scripts/accelerate_configs/deepspeed_zero2_config.yaml \
    opensora/train/train_t2v.py \
    --model LatteT2V-XL/122 \
    --text_encoder_name DeepFloyd/t5-v1_1-xxl \
    --dataset t2v \
    --ae CausalVAEModel_4x8x8 \
    --ae_path '/mnt/NVM/opensora/vae' \
    --data_path /mnt/NVM/opensora/caption.json \
    --video_folder /mnt/NVM/opensora/videos \
    --sample_rate 1 \
    --num_frames 65 \
    --max_image_size 512 \
    --gradient_checkpointing \
    --attention_mode xformers \
    --train_batch_size=1 \
    --dataloader_num_workers 10 \
    --gradient_accumulation_steps=2 \
    --max_train_steps=1000000 \
    --learning_rate=5e-06 \
    --lr_scheduler="constant" \
    --lr_warmup_steps=0 \
    --mixed_precision="bf16" \
    --checkpointing_steps=500 \
    --output_dir="/mnt/NVM/opensora" \
    --pretrained '/mnt/NVM/opensora/pretrained/diffusion_pytorch_model.pt'  \
    --use_deepspeed \
    --model_max_length 300 \
    --use_image_num 16 \
    --use_img_from_vid \
    --enable_tiling \
    --use_8bit_adam
```

I could train the model from scratch.

```bash
Steps:   0%|                       | 5/1000000 [01:10<3917:28:48, 14.10s/it, lr=5e-6, step_loss=1.3]
```

How can i do?

**Comment by LinB203** [comment]
Download from https://huggingface.co/maxin-cn/Latte/resolve/main/t2v.pt

**Comment by alfredplpl** [comment]
It seems good.

```bash
Steps:   0%|                                  | 1/1000000 [00:19<5409:55:43, 19.48s/it, lr=5e-6, step_loss=0.000419]
```

Thanks.

**Comment by justcode740** [comment]
@LinB203 Hey, I wonder why this finetune would take 5409 hours? Also I try to do little epoch and exit but the produced result make me think the model is trained from scratch even I am training with `--pretrained "./Open-Sora-Plan-v1.0.0/65x512x512/diffusion_pytorch_model.safetensors"`.

**Comment by justcode740** [comment]
> @LinB203 Hey, I wonder why this finetune would take so long, e.g. 5409 hours? Also I try to do little epoch and exit but the produced result make me think the model is trained from scratch even I am training with `--pretrained "./Open-Sora-Plan-v1.0.0/65x512x512/diffusion_pytorch_model.safetensors"`.

also wonder is [t2v](https://huggingface.co/maxin-cn)[https://huggingface.co/maxin-cn](https://huggingface.co/maxin-cn/Latte/resolve/main/t2v.pt) better than ./Open-Sora-Plan-v1.0.0/65x512x512/diffusion_pytorch_model.safetensors as a base model to continue training on?

**Comment by atomrun39** [comment]
> Download from https://huggingface.co/maxin-cn/Latte/resolve/main/t2v.pt

Hello, this link is no longer valid. How should I download the t2v.pt model for training train_videoae_65x256x256.sh.
