### ISSUE TITLE
How to Video Captioning

### ISSUE THREAD

**Issue by alfredplpl** [PKU-YuanGroup/Open-Sora-Plan#233]
Thank to your advice, I could finetune your model on Zudamon Anime dataset.
(I can use authorized Zudamon Anime dataset.)

https://github.com/PKU-YuanGroup/Open-Sora-Plan/assets/3625196/a76c1ebc-96ab-4b65-9f9b-7469b158d432

But, I could do video captioning few videos manually because the video captioning is hard.

```json
[
  {
    "path": "/mnt/my_raid/zunda_video/segment_113.mp4",
    "cap": ["Anime, a girl is talking in front of trees, open eyes, face, from side, brown short hair."]
  },
  {
    "path": "/mnt/my_raid/zunda_video/segment_145.mp4",
    "cap": ["Anime, a girl wearing white cap is talking in a machine, closed eyes, face, from front, blue short hair."]
  },
    {
    "path": "/mnt/my_raid/zunda_video/segment_325.mp4",
    "cap": ["Anime, a girl is talking with cloud backgroud, open eyes then closed eyes, face, from side, green long hair."]
  },
    {
    "path": "/mnt/my_raid/zunda_video/segment_422.mp4",
    "cap": ["Anime, a smiling girl is talking, open eyes, face, from front, black long hair."]
  }
]
```

According to your site, you use LLaVA for video captioning but the model is for image captioning.
How do you video captioning by LLaVA?

**Comment by LinB203** [comment]
Now v1.0.0 version for short videos we made some exploration, we can use the image captioning model to annotate the middle frame of the video. We think that the information in one frame of a 2-3 seconds video can contain almost the whole video.
We are exploring the pipeline for long video annotation. This will be available in the next release.

**Comment by alfredplpl** [comment]
Thanks.
I will try to do image captioning at the mid frame.
