### ISSUE TITLE
What's the difference between Open-Sora-Plan and Open-Sora?

### ISSUE THREAD

**Issue by bug-fixed** [PKU-YuanGroup/Open-Sora-Plan#248]
https://github.com/PKU-YuanGroup/Open-Sora-Plan

https://github.com/hpcaitech/Open-Sora

any thoughts? Thanks.

**Comment by LinB203** [comment]
Just find this. https://github.com/hpcaitech/Open-Sora/issues/99

**Comment by bug-fixed** [comment]
Hi @LinB203 , thanks for reply! Actually, I mean the differences in technique details.
