### ISSUE TITLE
[BUG] H100 training fails

### ISSUE THREAD

**Issue by DachengLi1** [PKU-YuanGroup/Open-Sora-Plan#264]
Hi there, thanks a lot for the great work! I tried to train some samples using H100, but seems there are some (numerical?) issues.

500 Steps using H100:
<img width="257" alt="Screenshot 2024-04-27 at 10 43 49 AM" src="https://github.com/PKU-YuanGroup/Open-Sora-Plan/assets/28548224/a671f77f-86d4-45f5-b868-5bf91411a0b0">

500 steps using A100:
<img width="258" alt="Screenshot 2024-04-27 at 10 43 09 AM" src="https://github.com/PKU-YuanGroup/Open-Sora-Plan/assets/28548224/22e6481b-736c-4535-b60f-c328efd448d3">

Is there any known library that does not support h100 in the repo? Thank you!

**Comment by LinB203** [comment]
Hi, we have tested on h100, and the result of 500 steps is similar with the result training on a100.

**Comment by DachengLi1** [comment]
<img width="362" alt="Screenshot 2024-04-28 at 12 02 54 AM" src="https://github.com/PKU-YuanGroup/Open-Sora-Plan/assets/28548224/81d49d39-f657-4f89-8667-16c2cd8f516a">
Thank you so much! I tried to train 500 steps on H100 and gives the above result (in k8s). Do you have any suggestion how I can debug this? From my experience, this "yellow circles" etc indicates the model has been corrupted and can not recover? Thank you so much for your help!

**Comment by LinB203** [comment]
I think you can directly load released weights to inference to eliminate code or environmental problems.

**Comment by DachengLi1** [comment]
Thank you! After reinstalling the environment, I found the H100 is well supported.
