### ISSUE TITLE
Warning, cannot find cuda-compiled version of RoPE2D, using a slow pytorch version instead

### ISSUE THREAD

**Issue by truedat101** [PKU-YuanGroup/Open-Sora-Plan#269]
Hi - when running server, get warning about slow pytorch.  While this is a warning, it sounds not optimized.  Is this a misconfiguration of how local pytorch was installed, or expected?

```
01:04 $ python -m opensora.serve.gradio_web_server
Warning, cannot find cuda-compiled version of RoPE2D, using a slow pytorch version instead
```

**Comment by LinB203** [comment]
Expected. We do not enable it.

**Comment by truedat101** [comment]
Great, was not sure, then closing.
