### ISSUE TITLE
Training memory for one node A100*8.

### ISSUE THREAD

**Issue by jiaxiangc** [PKU-YuanGroup/Open-Sora-Plan#302]
Greate work, a simple question about training.

If you train opensora using 65x512x512 dataset in A100-80G*8 with zero2_offload, the memory will be OOM? I just can train 65x384x384 dataset in this machine.

**Comment by fenghe12** [comment]
您好 请问您咋train起来的 我这里尝试训练的时候遇到了一点小问题

**Comment by jiaxiangc** [comment]
你可以post一下你的问题哈，一起解决解决。

**Comment by fenghe12** [comment]
您好 我遇到了相同的问题 请问您解决了吗

**Comment by LinB203** [comment]
> Greate work, a simple question about training.
> 
> If you train opensora using 65x512x512 dataset in A100-80G*8 with zero2_offload, the memory will be OOM? I just can train 65x384x384 dataset in this machine.

A batch size of 4 per GPU maybe consume ~40G.

**Comment by jiaxiangc** [comment]
> > Greate work, a simple question about training.
> > If you train opensora using 65x512x512 dataset in A100-80G*8 with zero2_offload, the memory will be OOM? I just can train 65x384x384 dataset in this machine.
> 
> A batch size of 4 per GPU maybe consume ~40G.

Yes, you are right. The problem has been solved, which caused by diffusers bugs.

**Comment by GloryyrolG** [comment]
> > Greate work, a simple question about training.
> > If you train opensora using 65x512x512 dataset in A100-80G*8 with zero2_offload, the memory will be OOM? I just can train 65x384x384 dataset in this machine.
> 
> A batch size of 4 per GPU maybe consume ~40G.

Hi @LinB203 ,

I tried debugging on a GPU and found that using only `.cuda` only took up 20G of GPU memory, while `accelerate` `deepspeed` took up more than 70G of GPU memory, leading to an OOM. Is this normal? Thanks for any help.

**Comment by GloryyrolG** [comment]
Hi @LinB203 et al.,

Moreover, 
**Q2.** `sp_size` > 1 seems to be found to make sampling in validation stuck?
