### ISSUE TITLE
Great work！A question about 65 frame inference reprocudtion.

### ISSUE THREAD

**Issue by jiaxiangc** [PKU-YuanGroup/Open-Sora-Plan#304]
I see your great results in https://github.com/PKU-YuanGroup/Open-Sora-Plan/blob/main/docs/Report-v1.1.0.md .
But we follow your configuration, the result is so normal. Do you know what reason it is?
![20240606-112406](https://github.com/PKU-YuanGroup/Open-Sora-Plan/assets/76088379/f45130fa-93e6-47b5-8569-7bbca58ebef9)

Thanks.

**Comment by LinB203** [comment]
The current data volume and model still need to be scaled.

**Comment by jiaxiangc** [comment]
> The current data volume and model still need to be scaled.

Looking forward to your next version model.

**Comment by LinB203** [comment]
> > The current data volume and model still need to be scaled.
> 
> Looking forward to your next version model.

Coming soon...
