### ISSUE TITLE
Does the order of sin and cos have a big impact in positional encoding?

### ISSUE THREAD

**Issue by AllenMao** [PKU-YuanGroup/Open-Sora-Plan#315]
https://github.com/PKU-YuanGroup/Open-Sora-Plan/blob/main/opensora/models/diffusion/utils/pos_embed.py#L72
“emb = np.concatenate([emb_sin, emb_cos], axis=1)  # (M, D)”，and general form "sin and cos are interlaced" diff?

**Comment by LinB203** [comment]
Sure, it sourced from [diffusers](https://github.com/huggingface/diffusers/blob/a9c403c00197d8d6eb854128dda2f7849cedd100/src/diffusers/models/embeddings.py#L70).
