### ISSUE TITLE
About Text encoder

### ISSUE THREAD

**Issue by jjihwan** [PKU-YuanGroup/Open-Sora-Plan#336]
Thank you for your dedicated effort.
Open-Sora Plan uses DeepFloyd/t5-v1_1-xxl as the text encoder.
Are there any differences between DeepFloyd/t5-v1_1-xxl and google/t5-v1_1-xxl?

It seems the google model has an encoder-decoder structure, while deepfloyd one has an encoder only structure.
Is deepfloyd's encoder the same as google's one?

Thanks!

**Comment by LinB203** [comment]
We just follow [Pixart](https://pixart-alpha.github.io/).

**Comment by jjihwan** [comment]
@LinB203 got it, thanks!
