### ISSUE TITLE
More details about training VAE.

### ISSUE THREAD

**Issue by serend1p1ty** [PKU-YuanGroup/Open-Sora-Plan#339]
> Similar to v1.0.0, we initialized from the Latent Diffusion's VAE and used tail initialization. For CausalVideoVAE, we trained for 100k steps in the first stage with a video shape of 9×256×256. Subsequently, we increased the frame count from 9 to 25 and found that this significantly improved the model's performance. It is important to clarify that we enabled the mixed factor during both the first and second stages, with a value of a (sigmoid(mixed factor)) reaching 0.88 at the end of training, indicating the model's tendency to retain low-frequency information. In the third stage, we reinitialized the mixed factor to 0.5 (sigmoid(0.5) = 0.6225), which further enhanced the model's capabilities.

# Q1: What's the initial value of mix factor?

# Q2: How many steps should each be trained in the following two stages?

**Comment by LinB203** [comment]
The initial value of mix factor is 0, meaning sigmoid(0)=0.5.
100k step each stage.

**Comment by serend1p1ty** [comment]
@LinB203 Thanks for your reply. What data do you use to train VAE? is it mixkit + pixels + pixabay?

**Comment by LinB203** [comment]
Arbitrary data is fine as it is a low level task. We've tried ucf101, kinetics400, or our data and they perform similarly.

**Comment by LinB203** [comment]
By the way, we found the 9 fps stage is not necessary, I would recommend training directly at 256 x 256 x 29 or 256 x 256 x 33.

**Comment by serend1p1ty** [comment]
@LinB203 Thank you very much!
