### ISSUE TITLE
Configuring CausalVAE v1.2 for Training

### ISSUE THREAD

**Issue by XinZhang0423** [PKU-YuanGroup/Open-Sora-Plan#353]
Hello,

I am currently training a CausalVAE model from scratch. According to the report for CausalVAE v1.2, the previous version's separated up/down temporal/spatial sampling methods have been replaced by a unified approach in v1.2. Could you please provide guidance on how to set the configuration file correctly for CausalVAE v1.2 to ensure it aligns with this unified sampling method? Thanks! 
对于Causalvae v1.2要如何配置config.json呢？十分感谢！

**Comment by qqingzheng** [comment]
https://huggingface.co/LanguageBind/Open-Sora-Plan-v1.2.0/blob/main/vae/config.json

**Comment by qqingzheng** [comment]
Due to code updates, some parameters in this config file are invalid, but it does not affect usage.

**Comment by Bravo5542** [comment]
请问您训练CausalVAE v1.2顺利吗？下面这个问题您是怎么解决的呢

Specific Issue: a missing file error

> File "Open-Sora-Plan/opensora/models/causalvideovae/model/losses/lpips.py", line 7, in
> from ...utils.taming_download import get_ckpt_path
> ModuleNotFoundError: No module named 'opensora.models.causalvideovae.utils.taming_download'

It appears that the taming_download module is missing from the opensora.models.causalvideovae.utils directory.
