### ISSUE TITLE
infer with npu for 93 ckpt for 4 card using sp error?

### ISSUE THREAD

**Issue by Edwardmark** [PKU-YuanGroup/Open-Sora-Plan#360]
Hi, thanks for your great work. I try to run with sample_t2v_sp.sh with 4 card with num_frames=93, but got the error:

[E OpParamMaker.cpp:273] call aclnnFlashAttentionScore failed, detail:EZ9999: Inner Error!
EZ9999: 2024-07-27-05:01:55.672.958  get unsupported atten_mask shape, the shape is [2, 1, 28800, 28800][FUNC:AnalyzeOptionalInput][FILE:flash_attention_score_tiling_general.cpp][LINE:1179]
        TraceBack (most recent call last):
        fail to analyze context info[FUNC:GetShapeAttrsInfo][FILE:flash_attention_score_tiling_general.cpp][LINE:689]
        Tiling failed
        Tiling Failed.
        Kernel Run failed. opType: 104, FlashAttentionScore
        launch failed for FlashAttentionScore, errno:561103.

**Comment by LinB203** [comment]
Hi, could you post your sample scripts?

**Comment by Edwardmark** [comment]
> Hi, could you post your sample scripts?

ASCEND_RT_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --nproc_per_node 4 --master_port 29888 \
    -m opensora.sample.sample_t2v_sp \
    --model_path /data2/dongbin/models/Open-Sora-Plan-v1.2.0/93x480p/ \
    --num_frames 93 \
    --height 480 \
    --width 640 \
    --cache_dir "../cache_dir" \
    --text_encoder_name /models/mt5-xxl \
    --text_prompt examples/prompt_list_0.txt \
    --ae CausalVAEModel_D4_4x8x8 \
    --ae_path //models/Open-Sora-Plan-v1.2.0/vae/ \
    --save_img_path "./sample_video_test" \
    --fps 24 \
    --guidance_scale 7.5 \
    --num_sampling_steps 100 \
    --enable_tiling \
    --tile_overlap_factor 0.125 \
    --save_memory \
    --max_sequence_length 512 \
    --sample_method EulerAncestralDiscrete \
    --model_type "dit"

**Comment by Edwardmark** [comment]
@LinB203 And the error is same if I change the resolution to 720p

**Comment by Edwardmark** [comment]
Sorry, it turns out that I change the code wrong. Thanks.
