### ISSUE TITLE
A training strategy similar to that of SD3, like cache the text embedding?

### ISSUE THREAD

**Issue by trouble-maker007** [PKU-YuanGroup/Open-Sora-Plan#361]
Have you tried caching the embeddings from text embedding or VAE encoding for further training? This could reduce the VRAM usage of MT5-XXL, but it's unclear whether it will affect the training performance.

**Comment by LinB203** [comment]
We think there should be no impact on performance, however it would require a lot of storage. In fact, the most significant overhead is not in vae or t5.

**Comment by trouble-maker007** [comment]
@LinB203 Understood, compared to text images, the sequence of video frames consumes more.
