### ISSUE TITLE
Confusion between rank and local_rank in train_causalvae.py

### ISSUE THREAD

**Issue by XinZhang0423** [PKU-YuanGroup/Open-Sora-Plan#369]
I encountered confusion between rank and local_rank in train_causalvae.py during multi-device training. I have resolved this by using torch.distributed.get_rank() for global operations like logging and saving checkpoint and os.environ["LOCAL_RANK"] for local device-specific operations like moving model, data to correspanding GPU. And some logging operations are not under the if rank==0 condition, which raises errors when using multiple devices. I suggest clearly documenting or commenting on the distinction between these variables to prevent similar confusion in the future.
我在使用 train_causalvae.py 进行多卡训练时遇到了 rank 和 local_rank 混淆的问题。

**Comment by qqingzheng** [comment]
Thank you!!! We will correct this confusion in the future.
