### ISSUE TITLE
v1.2 v.1.1 里的 scripts/causalvae/train.sh  区别很大 是不是提交错了？

### ISSUE THREAD

**Issue by jjk334** [PKU-YuanGroup/Open-Sora-Plan#374]
![image](https://github.com/user-attachments/assets/64050372-0d1e-4d20-a528-9697e31fcd2f)

**Comment by qqingzheng** [comment]
我们抛弃了pytorch_lightning的训练框架，所以训练脚本发生了比较大的改变。

**Comment by jjk334** [comment]
好的 谢谢
