### ISSUE TITLE
8 H100 finetune open sora plan 1.2.0 how to use sp_size and train_sp_batch_size

### ISSUE THREAD

**Issue by trouble-maker007** [PKU-YuanGroup/Open-Sora-Plan#378]
I use default sp_size 8 and train_sp_batch_size 2, raise CUDA out of memory
even with sp_size 1 and train_sp_batch_size 1, raise CUDA out of memory
but it can train on 1GPU with sp_size 1 and train_sp_batch_size 1
8 H100 are 8 machines, each with 1 GPU
training script use：https://github.com/PKU-YuanGroup/Open-Sora-Plan/blob/main/scripts/text_condition/gpu/train_t2v.sh

error message:
```
File "/usr/local/lib/python3.10/dist-packages/torch/optim/adamw.py", line 599, in _multi_tensor_adamw
exp_avg_sq_sqrt = torch._foreach_sqrt(device_exp_avg_sqs)
```

8 H100 are 8 machines, each with 1 GPU, is it not possible to configure sp_size > 1 and train_sp_batch_size > 1

**Comment by LinB203** [comment]
We do not support in your case. In our case each machine has 8 GPUs.

**Comment by trouble-maker007** [comment]
@LinB203 Thank you for your reply, it seems that the issue is with our cluster environment.

**Comment by GloryyrolG** [comment]
> I use default sp_size 8 and train_sp_batch_size 2, raise CUDA out of memory even with sp_size 1 and train_sp_batch_size 1, raise CUDA out of memory but it can train on 1GPU with sp_size 1 and train_sp_batch_size 1 8 H100 are 8 machines, each with 1 GPU training script use：https://github.com/PKU-YuanGroup/Open-Sora-Plan/blob/main/scripts/text_condition/gpu/train_t2v.sh
> 
> error message:
> 
> ```
> File "/usr/local/lib/python3.10/dist-packages/torch/optim/adamw.py", line 599, in _multi_tensor_adamw
> exp_avg_sq_sqrt = torch._foreach_sqrt(device_exp_avg_sqs)
> ```
> 
> 8 H100 are 8 machines, each with 1 GPU, is it not possible to configure sp_size > 1 and train_sp_batch_size > 1

Hi @trouble-maker007 @LinB203 

I found 1GPU `num_process=1`, `sp_size=1`, `train_sp_batch_size=1` encountered an [OOM problem](https://github.com/PKU-YuanGroup/Open-Sora-Plan/issues/302#issuecomment-2308435254) on 80G A100. What is the GPU memory of your H100? Thx,

**Comment by yuanzhi-zhu** [comment]
@trouble-maker007 How do you make it to train on 1GPU with sp_size 1 and train_sp_batch_size 1
