### ISSUE TITLE
神奇，image-to-video 得到的结果和参考图像完全不相关？

### ISSUE THREAD

**Issue by asdnjadsn** [PKU-YuanGroup/Open-Sora-Plan#391]
sample_inpaint.sh: 
prompt:rabbit
![image](https://github.com/user-attachments/assets/0e9b08ff-95cc-40ad-afab-2dda3716e3e0)
refer image: 1024 * 576
![6](https://github.com/user-attachments/assets/bb34de46-9d64-4bc7-9390-3c17519612a5)
result:
![image](https://github.com/user-attachments/assets/5031ce94-fa16-4b60-bf79-a1c4b8957a90)

**Comment by asdnjadsn** [comment]
好吧，有专门的i2v权重，我是傻子

**Comment by 281LinChenjian** [comment]
> 好吧，有专门的i2v权重，我是傻子

抱歉耽误您一点时间，当我运行T2V脚本的时候，我发现我生成的结果是错误的，这是我的运行脚本和结果，请问您能看出一点端倪吗？（我刚开始运行这段代码，如果问得太基础了，请别见怪）
![image](https://github.com/user-attachments/assets/3c49519b-5497-475c-b7fc-e173e8e81daa)
这是结果的显示，我不明白出了什么问题。
![image](https://github.com/user-attachments/assets/217b35e8-22e5-4307-b26e-1832b427601b)

**Comment by asdnjadsn** [comment]
> > 好吧，有专门的i2v权重，我是傻子
> 
> 抱歉耽误您一点时间，当我运行T2V脚本的时候，我发现我生成的结果是错误的，这是我的运行脚本和结果，请问您能看出一点端倪吗？（我刚开始运行这段代码，如果问得太基础了，请别见怪） ![image](https://private-user-images.githubusercontent.com/115632188/360308663-3c49519b-5497-475c-b7fc-e173e8e81daa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTIwMzMsIm5iZiI6MTcyNDMxMTczMywicGF0aCI6Ii8xMTU2MzIxODgvMzYwMzA4NjYzLTNjNDk1MTliLTU0OTctNDc1Yy1iN2ZjLWUxNzNlOGU4MWRhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQwNzI4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzM1NTgwM2VjZGU4MDNjNmU2ZWQ4MzkzMzI1M2NjYmI5YzRlYjY2NGNiNzY0ZjEyOTFkYzNhMTQxZTMwOWQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N5C-iV0AvALtYcIv1tGeAYmkqABc-ISJTaKvrwyiKwU) 这是结果的显示，我不明白出了什么问题。 ![image](https://private-user-images.githubusercontent.com/115632188/360308711-217b35e8-22e5-4307-b26e-1832b427601b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTIwMzMsIm5iZiI6MTcyNDMxMTczMywicGF0aCI6Ii8xMTU2MzIxODgvMzYwMzA4NzExLTIxN2IzNWU4LTIyZTUtNDMwNy1iMjZlLTE4MzJiNDI3NjAxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQwNzI4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNmExNGZhMTExMTg3NDQzMWQwMjI3MTM1MDZkOWUwMjVmYzJmZWViMmRjYzdmYmE2MTg5YzBkMDkyODk3MWZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NMij4pNl-D4icqUetZojZdyDx0Iu0gh7aTxxp0aGmME)

这结果看着应该是权重载入的不对，我没有跑1.0的，1.2的我试了一下还是可以的

**Comment by 281LinChenjian** [comment]
> > > 好吧，有专门的i2v权重，我是傻子
> > 
> > 
> > 抱歉耽误您一点时间，当我运行T2V脚本的时候，我发现我生成的结果是错误的，这是我的运行脚本和结果，请问您能看出一点端倪吗？（我刚开始运行这段代码，如果问得太基础了，请别见怪） ![image](https://private-user-images.githubusercontent.com/115632188/360308663-3c49519b-5497-475c-b7fc-e173e8e81daa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTIwMzMsIm5iZiI6MTcyNDMxMTczMywicGF0aCI6Ii8xMTU2MzIxODgvMzYwMzA4NjYzLTNjNDk1MTliLTU0OTctNDc1Yy1iN2ZjLWUxNzNlOGU4MWRhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQwNzI4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzM1NTgwM2VjZGU4MDNjNmU2ZWQ4MzkzMzI1M2NjYmI5YzRlYjY2NGNiNzY0ZjEyOTFkYzNhMTQxZTMwOWQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N5C-iV0AvALtYcIv1tGeAYmkqABc-ISJTaKvrwyiKwU) 这是结果的显示，我不明白出了什么问题。 ![image](https://private-user-images.githubusercontent.com/115632188/360308711-217b35e8-22e5-4307-b26e-1832b427601b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTIwMzMsIm5iZiI6MTcyNDMxMTczMywicGF0aCI6Ii8xMTU2MzIxODgvMzYwMzA4NzExLTIxN2IzNWU4LTIyZTUtNDMwNy1iMjZlLTE4MzJiNDI3NjAxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQwNzI4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNmExNGZhMTExMTg3NDQzMWQwMjI3MTM1MDZkOWUwMjVmYzJmZWViMmRjYzdmYmE2MTg5YzBkMDkyODk3MWZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NMij4pNl-D4icqUetZojZdyDx0Iu0gh7aTxxp0aGmME)
> 
> 这结果看着应该是权重载入的不对，我没有跑1.0的，1.2的我试了一下还是可以的

我跑的也是v1.2的，感觉确实是哪里出了问题。请问如果推理的帧数小于93帧或者我的分辨率和他提供的分辨率不对会导致如此差的效果吗

**Comment by asdnjadsn** [comment]
> > > > 好吧，有专门的i2v权重，我是傻子
> > > 
> > > 
> > > 抱歉耽误您一点时间，当我运行T2V脚本的时候，我发现我生成的结果是错误的，这是我的运行脚本和结果，请问您能看出一点端倪吗？（我刚开始运行这段代码，如果问得太基础了，请别见怪） ![image](https://private-user-images.githubusercontent.com/115632188/360308663-3c49519b-5497-475c-b7fc-e173e8e81daa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTIwMzMsIm5iZiI6MTcyNDMxMTczMywicGF0aCI6Ii8xMTU2MzIxODgvMzYwMzA4NjYzLTNjNDk1MTliLTU0OTctNDc1Yy1iN2ZjLWUxNzNlOGU4MWRhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQwNzI4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzM1NTgwM2VjZGU4MDNjNmU2ZWQ4MzkzMzI1M2NjYmI5YzRlYjY2NGNiNzY0ZjEyOTFkYzNhMTQxZTMwOWQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N5C-iV0AvALtYcIv1tGeAYmkqABc-ISJTaKvrwyiKwU) 这是结果的显示，我不明白出了什么问题。 ![image](https://private-user-images.githubusercontent.com/115632188/360308711-217b35e8-22e5-4307-b26e-1832b427601b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTIwMzMsIm5iZiI6MTcyNDMxMTczMywicGF0aCI6Ii8xMTU2MzIxODgvMzYwMzA4NzExLTIxN2IzNWU4LTIyZTUtNDMwNy1iMjZlLTE4MzJiNDI3NjAxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQwNzI4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNmExNGZhMTExMTg3NDQzMWQwMjI3MTM1MDZkOWUwMjVmYzJmZWViMmRjYzdmYmE2MTg5YzBkMDkyODk3MWZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NMij4pNl-D4icqUetZojZdyDx0Iu0gh7aTxxp0aGmME)
> > 
> > 
> > 这结果看着应该是权重载入的不对，我没有跑1.0的，1.2的我试了一下还是可以的
> 
> 我跑的也是v1.2的，感觉确实是哪里出了问题。请问如果推理的帧数小于93帧或者我的分辨率和他提供的分辨率不对会导致如此差的效果吗

应该影响不大

**Comment by JonathanLi19** [comment]
> > 好吧，有专门的i2v权重，我是傻子
> 
> 抱歉耽误您一点时间，当我运行T2V脚本的时候，我发现我生成的结果是错误的，这是我的运行脚本和结果，请问您能看出一点端倪吗？（我刚开始运行这段代码，如果问得太基础了，请别见怪） ![image](https://private-user-images.githubusercontent.com/115632188/360308663-3c49519b-5497-475c-b7fc-e173e8e81daa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MDA2MzYsIm5iZiI6MTcyNTgwMDMzNiwicGF0aCI6Ii8xMTU2MzIxODgvMzYwMzA4NjYzLTNjNDk1MTliLTU0OTctNDc1Yy1iN2ZjLWUxNzNlOGU4MWRhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQxMjU4NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzMxMGZjZWY5YmVmYzA4NGMwODQ2ZjUxMTgwMTAzNTIzMzE5M2VlMWJmMjRhMDVmMzdjYmZjZjUyZWE1OTVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JQ4Sgj79wE0iXXp8u_WvjB486lLBxznGuriGlG5EZUw) 这是结果的显示，我不明白出了什么问题。 ![image](https://private-user-images.githubusercontent.com/115632188/360308711-217b35e8-22e5-4307-b26e-1832b427601b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MDA2MzYsIm5iZiI6MTcyNTgwMDMzNiwicGF0aCI6Ii8xMTU2MzIxODgvMzYwMzA4NzExLTIxN2IzNWU4LTIyZTUtNDMwNy1iMjZlLTE4MzJiNDI3NjAxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQxMjU4NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNGE2YWY2YmZmOTE5MDhmNmM3MjQzNWI0OGYzZmM5MjgzMGRiZjg5ZjhiOWRhOWE0YjBjMDY2NDg0ZmVhYzIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q6KOsm7T-wL-Iirpv8jerZlZ7u4j1CO_6STblUlAglY)

请问你解决了这个问题了么 我也碰到这样的情况了

**Comment by LWang1016** [comment]
@asdnjadsn 您好，您方便指导下这个脚本有什么问题吗，我跑v1.2的模型，结果也是很奇怪，不合预期。

**Comment by JonathanLi19** [comment]
> @281LinChenjian 我尝试了93x720P的weight，是可以跑出正确结果的。

请问你的google/mt5-xxl是自己手动下载到吗，我直接用from_pretrained函数是不行的

**Comment by LWang1016** [comment]
> > @281LinChenjian 我尝试了93x720P的weight，是可以跑出正确结果的。
> 
> 请问你的google/mt5-xxl是自己手动下载的吗，我直接用from_pretrained函数是不行的

是的，手动下载的。29x480p的weight 文件应该有问题，我试了93x720p, 29x720p的，这两组都可以正常跑出结果。

**Comment by JonathanLi19** [comment]
> > > @281LinChenjian 我尝试了93x720P的weight，是可以跑出正确结果的。
> > 
> > 
> > 请问你的google/mt5-xxl是自己手动下载的吗，我直接用from_pretrained函数是不行的
> 
> 是的，手动下载的。29x480p的weight 文件应该有问题，我试了93x720p, 29x720p的，这两组都可以正常跑出结果。

奇怪 我后来又手动下载了google/mt5-xxl，并且使用的是93x720p的权重，还是很奇怪的结果
