### ISSUE TITLE
求开源29x480p的ckpt。

### ISSUE THREAD

**Issue by foreverpiano** [PKU-YuanGroup/Open-Sora-Plan#393]
stage3的ckpt可以开源下吗？

**Comment by foreverpiano** [comment]
@LinB203

**Comment by foreverpiano** [comment]
data 数据在huggingface还没有

**Comment by LinB203** [comment]
> stage3的ckpt可以开源下吗？

好的，已经开源到[HF](https://huggingface.co/LanguageBind/Open-Sora-Plan-v1.2.0/tree/main).

**Comment by LinB203** [comment]
> data 数据在huggingface还没有

请查看数据说明。https://huggingface.co/datasets/LanguageBind/Open-Sora-Plan-v1.2.0

**Comment by LinB203** [comment]
> hi @LinB203 et al.,
> 
> it seems the [29x480p ckpt](https://huggingface.co/LanguageBind/Open-Sora-Plan-v1.2.0/tree/main/29x480p) has problems?
> 
> A young man at his 20s is sitting on a piece of cloud in the sky, reading a book.
> 
>  EulerAncestralDiscrete_0___gs7.5_s20.mp4

This checkpoint should use lower cfg, e.g, 2.5.

**Comment by GloryyrolG** [comment]
> > hi @LinB203 et al.,
> > it seems the [29x480p ckpt](https://huggingface.co/LanguageBind/Open-Sora-Plan-v1.2.0/tree/main/29x480p) has problems?
> > A young man at his 20s is sitting on a piece of cloud in the sky, reading a book.
> > EulerAncestralDiscrete_0___gs7.5_s20.mp4
> 
> This checkpoint should use lower cfg, e.g, 2.5.

Thx for ur reply! i tried `cfg=2.5`.

1. Could I ask what determines whether `cfg` is set higher (7.5 for the others) or lower here (2.5)?
2. In addition, it is observed that the color tone is indeed greatly improved and close to the real color, but on the other hand, it seems that the quality of the generated portrait and body is not as good as `cfg=7.5` (like anime portrait but complete).

thx,

https://github.com/user-attachments/assets/5bb39c32-2639-4625-8337-ed8fa088061d
