### ISSUE TITLE
After finetune the model, inference still get noise.

### ISSUE THREAD

**Issue by wtjiang98** [PKU-YuanGroup/Open-Sora-Plan#396]
I fine tuned the 93x480p with my own collected video dataset and add the pose guidance for control sign. Here's a graph of the loss for my training, the training seems to be pretty good:
![image](https://github.com/user-attachments/assets/240e5320-86d8-4b68-8880-e06ffa91d549)

However, when I inference with the saved checkpoint, it produce noise result:

https://github.com/user-attachments/assets/69ef8ac9-e5fb-4731-bc84-921159a9be55

Then I try to simply decode the latent that obtain from the predicted noise when training via the following code:
`output_latent= noisy_model_input - model_pred`
`video = vae.decode(output_latent)`

https://github.com/user-attachments/assets/cac7a519-0c85-448e-9873-9d296deefe75

The result seems normal. I am wondering where is the problem and how can I solve this. Thank you! 

BTW: My issue is quite similar with #394. It seems to be a common problem.

**Comment by spacegoing** [comment]
@wtjiang98 genius

**Comment by wtjiang98** [comment]
> @wtjiang98 genius

Still don't know how to solve the problem. Should we modify the inference code?

**Comment by spacegoing** [comment]
> > @wtjiang98 genius
> 
> Still don't know how to solve the problem. Should we modify the inference code?

Ah I see. I thought u solved the issue LoL.  May I ask where did u add the part?

```
output_latent= noisy_model_input - model_pred
video = vae.decode(output_latent)
```

Since u can decode without noise, why problem not solved?

**Comment by spacegoing** [comment]
> > > @wtjiang98 genius
> > 
> > 
> > Still don't know how to solve the problem. Should we modify the inference code?
> 
> Ah I see. I thought u solved the issue LoL. May I ask where did u add the part?
> 
> ```
> output_latent= noisy_model_input - model_pred
> video = vae.decode(output_latent)
> ```
> 
> Since u can decode without noise, why problem not solved?

It's here https://github.com/PKU-YuanGroup/Open-Sora-Plan/blob/842435c016d358b6e6aa1ec788cbb593c5cdec32/opensora/train/train_t2v_diffusers.py#L631

**Comment by LinB203** [comment]
For fine-tuning, we offer the following suggestions:
1. Reduce the learning rate. We recommend a learning rate of 1e-5 to 1e-6 for fine-tuning.
2. If there are additional modules added, load the pre-trained weights and use zero init for inference. This will verify that the initialization or code is correct.
3. Always keep an eye on the loss curve, if there is spike loss, then it is very likely that the model has collapsed, resume training from the nearest checkpoint. If the training process crashes frequently, then consider increasing the batch size or continue to reduce the learning rate.

**Comment by spacegoing** [comment]
> For fine-tuning, we offer the following suggestions:
> 
> 1. Reduce the learning rate. We recommend a learning rate of 1e-5 to 1e-6 for fine-tuning.
> 2. If there are additional modules added, load the pre-trained weights and use zero init for inference. This will verify that the initialization or code is correct.
> 3. Always keep an eye on the loss curve, if there is spike loss, then it is very likely that the model has collapsed, resume training from the nearest checkpoint. If the training process crashes frequently, then consider increasing the batch size or continue to reduce the learning rate.

Hi Lin,

Many thanks for ur reply.

My loss curve is very similar to the posted one: Loss decrease without significant spike noticed. And decoding straight from train script https://github.com/PKU-YuanGroup/Open-Sora-Plan/blob/842435c016d358b6e6aa1ec788cbb593c5cdec32/opensora/train/train_t2v_diffusers.py#L631
outputs clear video without noise.

Yet inference from the checkpoint will output noisy videos.

I noticed the model is trained with DDPM scheduler but inferenced with Euler scheduler, could this cause the unstable case? How do I further debug this?

**Comment by wtjiang98** [comment]
> > For fine-tuning, we offer the following suggestions:
> > 
> > 1. Reduce the learning rate. We recommend a learning rate of 1e-5 to 1e-6 for fine-tuning.
> > 2. If there are additional modules added, load the pre-trained weights and use zero init for inference. This will verify that the initialization or code is correct.
> > 3. Always keep an eye on the loss curve, if there is spike loss, then it is very likely that the model has collapsed, resume training from the nearest checkpoint. If the training process crashes frequently, then consider increasing the batch size or continue to reduce the learning rate.
> 
> Hi Lin,
> 
> Many thanks for ur reply.
> 
> My loss curve is very similar to the posted one: Loss decrease without significant spike noticed. And decoding straight from train script
> 
> https://github.com/PKU-YuanGroup/Open-Sora-Plan/blob/842435c016d358b6e6aa1ec788cbb593c5cdec32/opensora/train/train_t2v_diffusers.py#L631
> 
> 
> outputs clear video without noise.
> Yet inference from the checkpoint will output noisy videos.
> 
> I noticed the model is trained with DDPM scheduler but inferenced with Euler scheduler, could this cause the unstable case? How do I further debug this?
> 
> My loss curve FYI, the lr is 43 --learning_rate=1e-4 \ :
> 
> <img alt="image" width="850" src="https://private-user-images.githubusercontent.com/5180020/359321943-fcaba83e-1cbe-4270-bd28-901249d73015.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMjM4NzAsIm5iZiI6MTcyNDEyMzU3MCwicGF0aCI6Ii81MTgwMDIwLzM1OTMyMTk0My1mY2FiYTgzZS0xY2JlLTQyNzAtYmQyOC05MDEyNDlkNzMwMTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjBUMDMxMjUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzJmODgxNTg4MDExMjYxNzY2OWQwODA0N2M3ZDg1ZjUyOGE1OWE4NTg5M2ZiYTM5NDY4MGI3MjRlNGIwNjBjMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6J5QTMygySGtQFOBYxz5SJQ6NrLSXL26mJC6Cv68r3U">

I also suspected that it is the scheduler problem, but I have changed the scheduler to DDPM when inference, still get noisy videos...

**Comment by spacegoing** [comment]
> > > For fine-tuning, we offer the following suggestions:
> > > 
> > > 1. Reduce the learning rate. We recommend a learning rate of 1e-5 to 1e-6 for fine-tuning.
> > > 2. If there are additional modules added, load the pre-trained weights and use zero init for inference. This will verify that the initialization or code is correct.
> > > 3. Always keep an eye on the loss curve, if there is spike loss, then it is very likely that the model has collapsed, resume training from the nearest checkpoint. If the training process crashes frequently, then consider increasing the batch size or continue to reduce the learning rate.
> > 
> > 
> > Hi Lin,
> > Many thanks for ur reply.
> > My loss curve is very similar to the posted one: Loss decrease without significant spike noticed. And decoding straight from train script
> > https://github.com/PKU-YuanGroup/Open-Sora-Plan/blob/842435c016d358b6e6aa1ec788cbb593c5cdec32/opensora/train/train_t2v_diffusers.py#L631
> > 
> > outputs clear video without noise.
> > Yet inference from the checkpoint will output noisy videos.
> > I noticed the model is trained with DDPM scheduler but inferenced with Euler scheduler, could this cause the unstable case? How do I further debug this?
> > My loss curve FYI, the lr is 43 --learning_rate=1e-4 \ :
> > <img alt="image" width="850" src="https://private-user-images.githubusercontent.com/5180020/359321943-fcaba83e-1cbe-4270-bd28-901249d73015.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMjM4NzAsIm5iZiI6MTcyNDEyMzU3MCwicGF0aCI6Ii81MTgwMDIwLzM1OTMyMTk0My1mY2FiYTgzZS0xY2JlLTQyNzAtYmQyOC05MDEyNDlkNzMwMTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjBUMDMxMjUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzJmODgxNTg4MDExMjYxNzY2OWQwODA0N2M3ZDg1ZjUyOGE1OWE4NTg5M2ZiYTM5NDY4MGI3MjRlNGIwNjBjMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6J5QTMygySGtQFOBYxz5SJQ6NrLSXL26mJC6Cv68r3U">
> 
> I also suspected that it is the scheduler problem, but I have changed the scheduler to DDPM when inference, still get noisy videos...

Me too

**Comment by wtjiang98** [comment]
> For fine-tuning, we offer the following suggestions:
> 
> 1. Reduce the learning rate. We recommend a learning rate of 1e-5 to 1e-6 for fine-tuning.
> 2. If there are additional modules added, load the pre-trained weights and use zero init for inference. This will verify that the initialization or code is correct.
> 3. Always keep an eye on the loss curve, if there is spike loss, then it is very likely that the model has collapsed, resume training from the nearest checkpoint. If the training process crashes frequently, then consider increasing the batch size or continue to reduce the learning rate.

I try loading the pre-trained weights and use zero init for inference, it looks good, seems that the initialization and code are correct. But when I change to my saved checkpoint, it still output noise videos. 

My question is: How can the loss curve seems good, the validation when training seems good, but fail on loading saved checkpoints for inference.

**Comment by LinB203** [comment]
> > For fine-tuning, we offer the following suggestions:
> > 
> > 1. Reduce the learning rate. We recommend a learning rate of 1e-5 to 1e-6 for fine-tuning.
> > 2. If there are additional modules added, load the pre-trained weights and use zero init for inference. This will verify that the initialization or code is correct.
> > 3. Always keep an eye on the loss curve, if there is spike loss, then it is very likely that the model has collapsed, resume training from the nearest checkpoint. If the training process crashes frequently, then consider increasing the batch size or continue to reduce the learning rate.
> 
> Hi Lin,
> 
> Many thanks for ur reply.
> 
> My loss curve is very similar to the posted one: Loss decrease without significant spike noticed at few thousands steps. And decoding straight from train script
> 
> https://github.com/PKU-YuanGroup/Open-Sora-Plan/blob/842435c016d358b6e6aa1ec788cbb593c5cdec32/opensora/train/train_t2v_diffusers.py#L631
> 
> 
> outputs clear video without noise.
> Yet inference from the checkpoint will output noisy videos.
> 
> I noticed the model is trained with DDPM scheduler but inferenced with Euler scheduler, could this cause the unstable case? How do I further debug this?
> 
> My loss curve FYI, the lr is 43 --learning_rate=1e-4 \ :
> 
> <img alt="image" width="850" src="https://private-user-images.githubusercontent.com/5180020/359321943-fcaba83e-1cbe-4270-bd28-901249d73015.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMjQ3MzEsIm5iZiI6MTcyNDEyNDQzMSwicGF0aCI6Ii81MTgwMDIwLzM1OTMyMTk0My1mY2FiYTgzZS0xY2JlLTQyNzAtYmQyOC05MDEyNDlkNzMwMTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjBUMDMyNzExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjVlZTMzN2Q3ZmM1NWJmODcxOTllOWJmZjRlMDQzZjdkYThkN2EyMDM0NDZlNzY1ZjgzZTNiOTA0NGRhZGQwYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bOFw8N1qr_5LMBZhbr1jzscOvX2p7GyLZH4IlE9Huug">

You can see spike-loss in 6.4k step. Could you inference with 6k checkpoint?

**Comment by LinB203** [comment]
> > 对于微调，我们提出以下建议：
> > 
> > 1. 降低学习率。我们建议使用 1e-5 到 1e-6 的学习率进行微调。
> > 2. 如果添加了其他模块，请加载预先训练的权重并使用零初始化进行推理。这将验证初始化或代码是否正确。
> > 3. 时刻关注loss曲线，如果出现loss的尖峰，那么很有可能模型崩溃了，从最近的checkpoint恢复训练。如果训练过程频繁崩溃，那么可以考虑增加batch size或者继续降低学习率。
> 
> 我尝试加载预训练的权重并使用零初始化进行推理，看起来不错，似乎初始化和代码是正确的。但是当我切换到我保存的检查点时，它仍然输出噪音视频。
> 
> 我的问题是：为什么损失曲线看起来不错，训练时的验证看起来不错，但在加载已保存的检查点进行推理时却失败了。

Do you have spike-loss? Maybe the learningrate is too high.

**Comment by wtjiang98** [comment]
> > > 对于微调，我们提出以下建议：
> > > 
> > > 1. 降低学习率。我们建议使用 1e-5 到 1e-6 的学习率进行微调。
> > > 2. 如果添加了其他模块，请加载预先训练的权重并使用零初始化进行推理。这将验证初始化或代码是否正确。
> > > 3. 时刻关注loss曲线，如果出现loss的尖峰，那么很有可能模型崩溃了，从最近的checkpoint恢复训练。如果训练过程频繁崩溃，那么可以考虑增加batch size或者继续降低学习率。
> > 
> > 
> > 我尝试加载预训练的权重并使用零初始化进行推理，看起来不错，似乎初始化和代码是正确的。但是当我切换到我保存的检查点时，它仍然输出噪音视频。
> > 我的问题是：为什么损失曲线看起来不错，训练时的验证看起来不错，但在加载已保存的检查点进行推理时却失败了。
> 
> Do you have spike-loss? Maybe the learningrate is too high.

The following is the loss curve without any smooth. It seems that there is no spike-loss. But the loss at the beginning is quite big. I would try to change my learning rate to 1e-5 or 1e-6.

![image](https://github.com/user-attachments/assets/236647ab-8974-4015-9006-5a45d84e8b73)

**Comment by spacegoing** [comment]
> > > 对于微调，我们提出以下建议：
> > > 
> > > 1. 降低学习率。我们建议使用 1e-5 到 1e-6 的学习率进行微调。
> > > 2. 如果添加了其他模块，请加载预先训练的权重并使用零初始化进行推理。这将验证初始化或代码是否正确。
> > > 3. 时刻关注loss曲线，如果出现loss的尖峰，那么很有可能模型崩溃了，从最近的checkpoint恢复训练。如果训练过程频繁崩溃，那么可以考虑增加batch size或者继续降低学习率。
> > 
> > 
> > 我尝试加载预训练的权重并使用零初始化进行推理，看起来不错，似乎初始化和代码是正确的。但是当我切换到我保存的检查点时，它仍然输出噪音视频。
> > 我的问题是：为什么损失曲线看起来不错，训练时的验证看起来不错，但在加载已保存的检查点进行推理时却失败了。
> 
> Do you have spike-loss? Maybe the learningrate is too high.

Yeah I tried checkpoints both before (500, 2500, 5000) and after (12500) the spike, they all outputs noisy videos

**Comment by LinB203** [comment]
For training from scratch, this is normal. The point of confusion for me is that if you guys are zero-init from pre-training weights, then the results should be seen very quickly and not be noisy. and from your descriptions you talk about how zero-init‘s model loaded with pre-training weights can reason directly to the normal video. Then everything looks normal, and the loss of its starting point shouldn't start at 1.x. In my experience there is no difference between a loss starting at 1.x and training from scratch.

**Comment by spacegoing** [comment]
> For training from scratch, this is normal. The point of confusion for me is that if you guys are zero-init from pre-training weights, then the results should be seen very quickly and not be noisy. and from your descriptions you talk about how zero-init‘s model loaded with pre-training weights can inference directly to the normal video.
> 
> I think the zero-init model should have a loss comparable to the previous loss value, but apparently it is not. The loss of its starting point shouldn't start at 1.x. In my experience there is no difference between a loss starting at 1.x and training from scratch.

Many thanks for your reply!

Would u pls elaborate on how to do "zero-init"? For now I'm not introducing any new modules into the model but simply finetune on my custom cartoon dataset instead.

**Comment by LinB203** [comment]
> > For training from scratch, this is normal. The point of confusion for me is that if you guys are zero-init from pre-training weights, then the results should be seen very quickly and not be noisy. and from your descriptions you talk about how zero-init‘s model loaded with pre-training weights can inference directly to the normal video.
> > I think the zero-init model should have a loss comparable to the previous loss value, but apparently it is not. The loss of its starting point shouldn't start at 1.x. In my experience there is no difference between a loss starting at 1.x and training from scratch.
> 
> Many thanks for your reply!
> 
> Would u pls elaborate on how to do "zero-init"? For now I'm not introducing any new modules into the model but simply finetune on my custom cartoon dataset instead.

Well, if you didn't add the new module additionally, the situation is even more unusual. The loss shouldn't be so high after you loaded the pre-training weights. Please make sure your pre-training weights are loaded. Can you post your script?

**Comment by spacegoing** [comment]
> > > For training from scratch, this is normal. The point of confusion for me is that if you guys are zero-init from pre-training weights, then the results should be seen very quickly and not be noisy. and from your descriptions you talk about how zero-init‘s model loaded with pre-training weights can inference directly to the normal video.
> > > I think the zero-init model should have a loss comparable to the previous loss value, but apparently it is not. The loss of its starting point shouldn't start at 1.x. In my experience there is no difference between a loss starting at 1.x and training from scratch.
> > 
> > 
> > Many thanks for your reply!
> > Would u pls elaborate on how to do "zero-init"? For now I'm not introducing any new modules into the model but simply finetune on my custom cartoon dataset instead.
> 
> Well, if you didn't add the new module additionally, the situation is even more unusual. The loss shouldn't be so high after you loaded the pre-training weights. Please make sure your pre-training weights are loaded. Can you post your script?

Hi Lin,

Good news, after using pre-training my sft works now! Thanks so much!

Is there any QR code / sponsor link that I can use to buy u a beer?

Thanks again for your help!

**Comment by wtjiang98** [comment]
> > > > For training from scratch, this is normal. The point of confusion for me is that if you guys are zero-init from pre-training weights, then the results should be seen very quickly and not be noisy. and from your descriptions you talk about how zero-init‘s model loaded with pre-training weights can inference directly to the normal video.
> > > > I think the zero-init model should have a loss comparable to the previous loss value, but apparently it is not. The loss of its starting point shouldn't start at 1.x. In my experience there is no difference between a loss starting at 1.x and training from scratch.
> > > 
> > > 
> > > Many thanks for your reply!
> > > Would u pls elaborate on how to do "zero-init"? For now I'm not introducing any new modules into the model but simply finetune on my custom cartoon dataset instead.
> > 
> > 
> > Well, if you didn't add the new module additionally, the situation is even more unusual. The loss shouldn't be so high after you loaded the pre-training weights. Please make sure your pre-training weights are loaded. Can you post your script?
> 
> Hi Lin,
> 
> Good news, after using pre-training my sft works now! Thanks so much!
> 
> Is there any QR code / sponsor link that I can use to buy u a beer?
> 
> Thanks again for your help!

So your problem is that you didn't load pretrain model, and directly train on your custom cartoon dataset? Then you load the pretrain model to solve it.

**Comment by spacegoing** [comment]
> > > > > For training from scratch, this is normal. The point of confusion for me is that if you guys are zero-init from pre-training weights, then the results should be seen very quickly and not be noisy. and from your descriptions you talk about how zero-init‘s model loaded with pre-training weights can inference directly to the normal video.
> > > > > I think the zero-init model should have a loss comparable to the previous loss value, but apparently it is not. The loss of its starting point shouldn't start at 1.x. In my experience there is no difference between a loss starting at 1.x and training from scratch.
> > > > 
> > > > 
> > > > Many thanks for your reply!
> > > > Would u pls elaborate on how to do "zero-init"? For now I'm not introducing any new modules into the model but simply finetune on my custom cartoon dataset instead.
> > > 
> > > 
> > > Well, if you didn't add the new module additionally, the situation is even more unusual. The loss shouldn't be so high after you loaded the pre-training weights. Please make sure your pre-training weights are loaded. Can you post your script?
> > 
> > 
> > Hi Lin,
> > Good news, after using pre-training my sft works now! Thanks so much!
> > Is there any QR code / sponsor link that I can use to buy u a beer?
> > Thanks again for your help!
> 
> So your problem is that you didn't load pretrain model, and directly train on your custom cartoon dataset? Then you load the pretrain model to solve it.

yes exactly LoL. I'd also love to know what zero-init means though...

**Comment by ZXMMD** [comment]
> > > > For training from scratch, this is normal. The point of confusion for me is that if you guys are zero-init from pre-training weights, then the results should be seen very quickly and not be noisy. and from your descriptions you talk about how zero-init‘s model loaded with pre-training weights can inference directly to the normal video.
> > > > I think the zero-init model should have a loss comparable to the previous loss value, but apparently it is not. The loss of its starting point shouldn't start at 1.x. In my experience there is no difference between a loss starting at 1.x and training from scratch.
> > > 
> > > 
> > > Many thanks for your reply!
> > > Would u pls elaborate on how to do "zero-init"? For now I'm not introducing any new modules into the model but simply finetune on my custom cartoon dataset instead.
> > 
> > 
> > Well, if you didn't add the new module additionally, the situation is even more unusual. The loss shouldn't be so high after you loaded the pre-training weights. Please make sure your pre-training weights are loaded. Can you post your script?
> 
> Hi Lin,
> 
> Good news, after using pre-training my sft works now! Thanks so much!
> 
> Is there any QR code / sponsor link that I can use to buy u a beer?
> 
> Thanks again for your help!

How can I correctly load pre-trained weights? Could you please share a script for loading pre-trained weights?  Thanks very much!

**Comment by wtjiang98** [comment]
It's the zero-init problem. After use the correct zero-init, the loss begin at 0.03. The inference results are not noise. Many thanks to @LinB203 for the insightful suggestion.

**Comment by 1KE-JI** [comment]
> spacegoing

Hi bro, I would like to ask what your successful experience is, and what hyperparameters did you use to train 480p? When I adjusted the learning rate to 1e-6, the inference was still noisy.

**Comment by spacegoing** [comment]
> > spacegoing
> 
> Hi bro, I would like to ask what your successful experience is, and what hyperparameters did you use to train 480p? When I adjusted the learning rate to 1e-6, the inference was still noisy.

as Lin suggested (I guess u missed the training section in readme), there are two modes: load from checkpoint and pretrain mode. 

when changing dataset, u need to use the pretrain mode

**Comment by 1KE-JI** [comment]
> > > spacegoing
> > 
> > 
> > Hi bro, I would like to ask what your successful experience is, and what hyperparameters did you use to train 480p? When I adjusted the learning rate to 1e-6, the inference was still noisy.
> 
> as Lin suggested (I guess u missed the training section in readme), there are two modes: load from checkpoint and pretrain mode.
> 
> when changing dataset, u need to use the pretrain mode

Yes, I do use the --pretrained parameter to load the open-sora-plan 93*480p checkpoint and the training loss is begin with 0.09. I want to ask what is the "pretrain mode"

**Comment by spacegoing** [comment]
@1KE-JI That's exactly what I meant. In this case we have different problems. Maybe reopen this issue / create a new one with more details. I'll help u debug.
