### ISSUE TITLE
使用enable_tiling会导致重建结果很差

### ISSUE THREAD

**Issue by wpy1999** [PKU-YuanGroup/Open-Sora-Plan#423]
感谢贵组出色的工作和开源精神。在使用VAE时我遇到了一个小问题，当调用eval_prepare.sh  -- enable_tiling重建分辨率>256的视频会存在不同tile区域色泽和原视频对不上的问题。附件是原视频和resolution=512, tile_overlap_factor=0.25的重建结果。重建结果在不同的tile区域存在色泽偏差。而如果不用-- enable_tiling则能正常重建，并且在我的测试512分辨率重建指标时，不用-- enable_tiling的指标远优于使用enable_tiling。请问贵组是否遇到这种情况，还是因为我环境等因素导致的。期待您的解答。

<img width="371" alt="1725286015259_A9819689-0E23-4a44-9276-9C289D5C54B8" src="https://github.com/user-attachments/assets/aa9230c1-a90d-493d-a30e-38f7c6a2477e">

原视频  https://github.com/user-attachments/assets/e0079565-00c3-409e-9221-1e1bb8eaee71

重建视频 https://github.com/user-attachments/assets/1ad29a4d-2a59-48f0-825d-2652c851484e

**Comment by qqingzheng** [comment]
我们也存在，这个问题是有损的tiling导致的。可以通过调整tile_overlap_factor参数来缓解这个问题。

我们会在下一个版本改进vae架构和提出无损tiling的方法，请关注下一个版本的更新。
