### ISSUE TITLE
The Panda70M_HQ1M annotation file has captions mismatch with Panda-70M offical annotation file

### ISSUE THREAD

**Issue by wtomin** [PKU-YuanGroup/Open-Sora-Plan#425]
I notice that the [Panda70M_HQ1M.json](https://huggingface.co/datasets/LanguageBind/Open-Sora-Plan-v1.2.0/tree/main/anno_json) released by Open-Sora-Plan has some differences with the Panda-70M offical annotation file (I downloaded [Training (10M) csv file](https://drive.google.com/file/d/1Lrsb65HTJ2hS7Iuy6iPCmjoc3abbEcAX/view) from [Panda70M](https://github.com/snap-research/Panda-70M?tab=readme-ov-file)).

For example, the video id `--SaHeTEmoE`'s captions in [Panda70M_HQ1M.json](https://huggingface.co/datasets/LanguageBind/Open-Sora-Plan-v1.2.0/tree/main/anno_json)  are:
```json
  {
    "path": "panda70m_part_0/--SaHeTEmoE/--SaHeTEmoE_segment_0.mp4",
    "cap": [
      "A man with blue hair is standing on a wood floor in a library full of books."
    ],
    "size": 7737015,
    "resolution": {
      "height": 1080,
      "width": 1920
    },
    "fps": 25.0,
    "duration": 16.76,
    "display_aspect_ratio": "16:9"
  },
  {
    "path": "panda70m_part_0/--SaHeTEmoE/--SaHeTEmoE_segment_1.mp4",
    "cap": [
      "A man with blue hair is standing in front of a bookshelf and talking to the camera."
    ],
    "size": 1099499,
    "resolution": {
      "height": 1080,
      "width": 1920
    },
    "fps": 25.0,
    "duration": 3.16,
    "display_aspect_ratio": "16:9"
  },
```

While in [Training (10M) csv file](https://drive.google.com/file/d/1Lrsb65HTJ2hS7Iuy6iPCmjoc3abbEcAX/view) from [Panda70M](https://github.com/snap-research/Panda-70M?tab=readme-ov-file), they are:
```csv
--SaHeTEmoE,https://www.youtube.com/watch?v=--SaHeTEmoE,"[['0:05:09.720', '0:05:12.040'], ['0:15:55.440', '0:15:58.840'], ['0:16:39.440', '0:16:45.320']]","['A couple of pictures of buses and people on the street.', 'A person is holding a stack of metal screws in their hand.', 'A close up of a person squeezing a blue block.']","[0.4765625, 0.4482421875, 0.4462890625]"
```

I haved checked the downloaded  [Panda70M](https://github.com/snap-research/Panda-70M?tab=readme-ov-file) dataset, and found the [Training (10M) csv file](https://drive.google.com/file/d/1Lrsb65HTJ2hS7Iuy6iPCmjoc3abbEcAX/view) was correct in this case. 

I am wondering if I have downloaded the wrong dataset that has the wrong video id, or there are some noises in [Panda70M_HQ1M.json](https://huggingface.co/datasets/LanguageBind/Open-Sora-Plan-v1.2.0/tree/main/anno_json)?

**Comment by LinB203** [comment]
We use [Training (full)](https://drive.google.com/file/d/1DeODUcdJCEfnTjJywM-ObmrlVg-wsvwz/view?usp=sharing). 
Each split from panda70m may have different timestamp.

`--SaHeTEmoE,https://www.youtube.com/watch?v=--SaHeTEmoE,"[['0:00:07.920', '0:00:24.680'], ...]","['A man with blue hair is standing on a wood floor in a library full of books.', ..."
`

**Comment by wtomin** [comment]
Thanks for your quick reply. It has solved my problem perfectly.
