### ISSUE TITLE
Poor T2V result

### ISSUE THREAD

**Issue by JonathanLi19** [PKU-YuanGroup/Open-Sora-Plan#436]
I use the following command to generate video from text (prompt_list_demo.txt contains 2 lines of text prompt):
CUDA_VISIBLE_DEVICES=0 python opensora/sample/sample_t2v.py \
    --model_path Open-Sora-Plan-v1.2.0/93x720p \
    --num_frames 29 \
    --height 480 \
    --width 640 \
    --cache_dir "./cache_dir" \
    --text_encoder_name google/mt5-xxl \
    --text_prompt examples/prompt_list_demo.txt \
    --ae CausalVAEModel_D4_4x8x8 \
    --ae_path Open-Sora-Plan-v1.2.0/vae \
    --save_img_path "./sample_video_29x480p_cfg7.5_step100" \
    --fps 24 \
    --guidance_scale 7.5 \
    --num_sampling_steps 100 \
    --enable_tiling \
    --max_sequence_length 512 \
    --sample_method EulerAncestralDiscrete \
    --model_type "dit"
However, my generated video quality is very poor. 
(P.S. I manually download LanguageBind/Open-Sora-Plan-v1.2.0 from huggingface to my machine. And google/mt5-xxl is not downloaded manually. Could this be the problem?)

https://github.com/user-attachments/assets/4a5f768f-f889-4e0e-bcd5-b9868e556ae5

**Comment by LWang1016** [comment]
@JonathanLi19   Me too, I also run the similar results which is not as exception.

**Comment by JonathanLi19** [comment]
> @JonathanLi19 Me too, I also run the similar results which is not as exception.

https://github.com/PKU-YuanGroup/Open-Sora-Plan/issues/391#issuecomment-2303868333
This guy here also generate the similar result.

**Comment by JonathanLi19** [comment]
Problem solved: I used 93x720p weight to generate video of 29 frames. That's why the video is very strange. When I change to 93 frames, it works fine.
