### ISSUE TITLE
Multiple resolution problem

### ISSUE THREAD

**Issue by JonathanLi19** [PKU-YuanGroup/Open-Sora-Plan#439]
Hi, great work! I have one question about Multiple resolution.
In docs/Report-v1.2.0.md,  you point out that by using **Bucket** training strategy, you can use multiple resolution and multiple length of videos for training. However, the weights released (e.g. 93x720p, 93x480p, etc.) only support video generation with a fixed length and resolution. I want to ask why there is not a weight that support multiple length and resolution videos' generation?

**Comment by JonathanLi19** [comment]
<img width="1061" alt="image" src="https://github.com/user-attachments/assets/a6f2a483-f33a-4454-91f4-60b5b75eac14">
It seems that **the Bucket training strategy** isn't used in v1.2.0.

**Comment by LinB203** [comment]
Yes, we use in next version.

**Comment by JonathanLi19** [comment]
Thanks for your answer!
