### ISSUE TITLE
could you share latent8_3d-lr1.00e-05-bs1-rs320-sr2-fr25/checkpoint-14000.ckpt

### ISSUE THREAD

**Issue by zhan-xu** [PKU-YuanGroup/Open-Sora-Plan#453]
Hi team, great work. Wondering if you could share the checkpoint of causalVAE training. The current ckpt you are sharing only has the VAE part, but no discriminator, optimizer_state and scalar_state. I am thinking to resume from your ckpt to continue training. Thanks!

**Comment by LinB203** [comment]
We are about to discard this version of VAE. as we will release a stronger, lower cost VAE.

**Comment by zhan-xu** [comment]
ok, thanks!
