### ISSUE TITLE
About CausalVideoVAE evaluation

### ISSUE THREAD

**Issue by sen-ye** [PKU-YuanGroup/Open-Sora-Plan#465]
Hello, I'm trying to reproduce the results of Table1 in your paper.
![233a167e3f5b9b92d7eb343759109df7](https://github.com/user-attachments/assets/1dd94213-a910-4b5b-9aa6-cd099fa5cf72)
Could you please specify more details on the evaluation part, e.g. fps, frame stride, full or subset validation set. Thanks.

**Comment by cnsdqd-dyb** [comment]
I'm trying to reproduce the results with your vae/Open-Sora-Plan/scripts/causalvae/prepare_eval.sh
There are some parameters here:
SAMPLE_RATE=1
NUM_FRAMES=33 (I guess need to be set with 25 refer your paper)
RESOLUTION=512 (I guess need to be set with 256 refer your paper)
SUBSET_SIZE=1
Could you please specify more details on the evaluation part, e.g. fps, frame stride, full or subset validation set. Thanks.

**Comment by LiuhanChen-github** [comment]
fps=24, frame=33, stride=1, full set, but we download the video by the code of panda70m and maybe a few of videos is unavailable for the failure of download.

**Comment by LiuhanChen-github** [comment]
resolution 256x256
