### ISSUE TITLE
About the 100k high-quality video data

### ISSUE THREAD

**Issue by ChrisLiu6** [PKU-YuanGroup/Open-Sora-Plan#467]
First, thank you very much for all you have done for the community!!

My question is about your released training data, specifically the 100k high-quality videos. I notice that the total size of files on https://huggingface.co/datasets/LanguageBind/Open-Sora-Plan-v1.1.0 is really large, so I wonder if all these videos belong to the 100k high-quality training samples, or the 100k samples are only a subset of the all the released data? If the second case, would it be possible for you to provide a minimal pack covering only the necessary video for recovering the 100k samples? As it would take a long time and much storage to download the full set. Many thanks!

**Comment by LinB203** [comment]
Sorry, we don't have a folder collection for this subset. It's just specified via our json.
