### ISSUE TITLE
Missing Model Error During Inference on Single Node

### ISSUE THREAD

**Issue by yachty66** [PKU-YuanGroup/Open-Sora-Plan#481]
## Problem
I'm encountering a missing model error when attempting to run the model on inference with a single node.

## Current Situation
- Trying to run inference on one node
- Consistently getting a missing model error
- No existing script for downloading the models automatically

## Questions
1. Do I need to download the models manually?
2. Is there a script or process for automatically downloading the required models?

**Comment by LinB203** [comment]
Sorry, you need download the models manually.
First, you need to download checkpoint including [diffusion model](https://huggingface.co/LanguageBind/Open-Sora-Plan-v1.3.0/tree/main/any93x640x640), [vae](https://huggingface.co/LanguageBind/Open-Sora-Plan-v1.3.0/tree/main/vae) and [text encoder](https://huggingface.co/google/mt5-xxl).
Then, modify `--model_path`, `--text_encoder_name_1` and `--ae_path` the path in [script](https://github.com/PKU-YuanGroup/Open-Sora-Plan/blob/main/scripts/text_condition/gpu/sample_t2v_v1_3.sh#L4).

**Comment by yachty66** [comment]
Yes got it, thanks

**Comment by yachty66** [comment]
I see you added it now already https://github.com/PKU-YuanGroup/Open-Sora-Plan/commit/41e81de7cacc4770f1fc648d93ffd2973c96e3e0#diff-ac6ac22c6fc92efc50b92cc60e88898025b0f8fb3b06dee1b0f4e582cdaf0d4eR127
