### ISSUE TITLE
有没有完整视频生成代码示例？

### ISSUE THREAD

**Issue by gobigrassland** [PKU-YuanGroup/Open-Sora-Plan#483]
https://huggingface.co/LanguageBind/Open-Sora-Plan-v1.3.0 这里没有没有写
而通过Gradio Web UI方式，由于GPU远程网络限制问题，无法启动gradio.   有没有直接加载模型将生成视频保存下来，像Huggingface大多数模型那样提供推理示例？

**Comment by gobigrassland** [comment]
opensora/serve/gradio_web_server.py
parser.add_argument('--', action='store_true')   这块代码漏写了什么参数吗？

**Comment by LinB203** [comment]
hi，技术报告只写我们的研发历程。具体的代码用法你可以到docs下面的文档查看，例如运行文本生成视频的[文档](https://github.com/PKU-YuanGroup/Open-Sora-Plan/blob/main/docs/T2V.md#inference)。

> https://huggingface.co/LanguageBind/Open-Sora-Plan-v1.3.0 这里没有没有写 而通过Gradio Web UI方式，由于GPU远程网络限制问题，无法启动gradio. 有没有直接加载模型将生成视频保存下来，像Huggingface大多数模型那样提供推理示例？

**Comment by LinB203** [comment]
> opensora/serve/gradio_web_server.py parser.add_argument('--', action='store_true') 这块代码漏写了什么参数吗？

感谢指出，已经修复。
