### ISSUE TITLE
Best Practices for Small-Scale Open-Sora Training Data?

### ISSUE THREAD

**Issue by yachty66** [PKU-YuanGroup/Open-Sora-Plan#484]
I'm gearing up to do some fine-tuning experiments with Open-Sora in my free time. Could you give me a quick rundown on what makes ideal training data for a small-scale setup?

Specifically, I'm wondering:
1. What types of videos work best?
2. Any tips for creating good captions?
3. How much data do I need for a meaningful experiment?

Thanks for all your hard work on this project!

**Comment by LinB203** [comment]
1. High aesthetic, no watermark, high resolution,more motion video are prefered. Fine-tuning anime-style videos is especially easy and satisfying.
2. I think qwen2-vl is a suitable captioner.
3. I'd conservatively estimate that about hundreds of videos would fine-tune a anime style video generated model. A few thousand would be even better.

**Comment by yachty66** [comment]
Thank you! Really valuable insight. I started by trying to train for the issues I'm facing there. I will make a new issue.
