### ISSUE TITLE
is Skiparse attn only useful in very long tokens(high resolution)

### ISSUE THREAD

**Issue by Stick-To** [PKU-YuanGroup/Open-Sora-Plan#488]
we use Skiparse attn to replace full attn in our 28 layer model, sparse1d= if i > 1 and i < 24, ,sparse_n=2,  sparse_group=i % 2 == 1, but could not recover baseline result; we train our model use 240p video, is Skiparse attn only useful with very long tokens(high resolution)?

**Comment by LinB203** [comment]
Not sure what your final result looks like, you can put your log as well as the result to help us analyse it better.
