### ISSUE TITLE
Missing weights for vae

### ISSUE THREAD

**Issue by Penitto** [PKU-YuanGroup/Open-Sora-Plan#489]
Hi there! 
I downloaded vae weights from [hf](https://huggingface.co/LanguageBind/Open-Sora-Plan-v1.3.0/tree/main). When I launch inference script I see warning about missing keys in model weights. Is it ok?
![image](https://github.com/user-attachments/assets/34f318f8-a56a-4a8b-a9ea-91e42ba6d741)

**Comment by LinB203** [comment]
That's ok, you can try to reconstruct video or image by [this](https://github.com/PKU-YuanGroup/Open-Sora-Plan/tree/main/scripts/causalvae).

**Comment by Penitto** [comment]
But I don't want to reconstruct video or image. I want to use text2video model 

> That's ok, you can try to reconstruct video or image by [this](https://github.com/PKU-YuanGroup/Open-Sora-Plan/tree/main/scripts/causalvae).

**Comment by qqingzheng** [comment]
it's ok, the weights of these misses are all hardcoded in the code.
