### ISSUE TITLE
assets

### ISSUE THREAD

**Issue by qqingzheng** [PKU-YuanGroup/Open-Sora-Plan#497]
<img width="899" alt="SCR-20241023-tzct" src="https://github.com/user-attachments/assets/03615e1d-2633-4247-af0b-d93e2a935e3e">
<img width="765" alt="SCR-20241023-tzwz" src="https://github.com/user-attachments/assets/f7d4f225-5d22-4152-90ad-32716884ae6c">

**Comment by LinB203** [comment]
![image](https://github.com/user-attachments/assets/57f1e31e-12eb-4713-ba47-409b0e0f8cce)

**Comment by LinB203** [comment]
![image](https://github.com/user-attachments/assets/af21a577-e5a8-46ac-8be4-0cd08cddb6c6)

**Comment by LinB203** [comment]
[算法工程师招聘-兔展智能.pdf](https://github.com/user-attachments/files/19107972/-.pdf)
