### ISSUE TITLE
tips on dataset volume for fine-tuning

### ISSUE THREAD

**Issue by junsukha** [PKU-YuanGroup/Open-Sora-Plan#500]
Hi!

Do you have any suggestions on the dataset volume needed for fine-tuning?
My purpose is to generate videos of specifically dynamic car movements such as car driving on the road. 

How many hours of car videos do you suggest to fine-tune with?

Appreciate sharing the work.

**Comment by LinB203** [comment]
High aesthetic, no watermark, high resolution,more motion video are prefered.  Qwen2-vl is a suitable captioner.
I'd conservatively estimate that about thousands of video clips would fine-tune a video generated model.

**Comment by junsukha** [comment]
@LinB203 thx! what length are you assuming for videos? 93 frames as you trained at the last training phase in v1.3?

**Comment by LinB203** [comment]
> @LinB203 thx! what length are you assuming for videos? 93 frames as you trained at the last training phase in v1.3?

Yes.
