### ISSUE TITLE
请问一下，我看这个模型示意图，提到了condition encoder

### ISSUE THREAD

**Issue by tangdong1994** [PKU-YuanGroup/Open-Sora-Plan#509]
![image](https://github.com/user-attachments/assets/8760692f-96fd-4715-ba3b-4a4eef0969e9)
请问一下，我看这个模型示意图，提到了condition encoder，但是我看代码里面好像没看到这个模型的定义

**Comment by LinB203** [comment]
这是我们正在做的下游任务，即将推出~
