### ISSUE TITLE
Fix /sample/pipeline_inpaint.py in main

### ISSUE THREAD

**Issue by slapst4r** [PKU-YuanGroup/Open-Sora-Plan#521]
i think there is a but in pipeline_inpaint.py in main at 161 line:
if not isinstance(noise_strength, float) or not (noise_strength >= 0 noise_strength <= 1):

probable solution:
if not isinstance(noise_strength, float) or not (noise_strength >= 0 **and** noise_strength <= 1):

**Comment by LinB203** [comment]
Fixed.
