### ISSUE TITLE
Confusion about the Norm method used in WFVAE.

### ISSUE THREAD

**Issue by Chester-CS** [PKU-YuanGroup/Open-Sora-Plan#526]
<img width="1242" alt="image" src="https://github.com/user-attachments/assets/3626e9e1-657b-436c-87fe-14073de0c68c">

Hello developers:

Thank you for your contributions to the T2V open-source. While reading the documentation for OpenSora-1.3, I noticed that in the design of WFVAE, there are multiple mentions of replacing GroupNorm with LayerNorm, suggesting that only with this replacement can Causal Cache be supported. However, my understanding is that both GroupNorm and LayerNorm operate on the channel dimension, which seems to have no inherent connection to temporal chunking and should not violate the causal property. For example, the normalization method used in CogVideoX is GroupNorm, yet it also implements Causal Cache.

I am somewhat confused about this and would like to know your thoughts.

OpenSoraPlan的开发者们你好：
    感激你们为T2V开源工作做出的贡献，我在阅读OpenSora-1.3的Doc中发现，在WFVAE的设计中多次提到了将GroupNorm替换为LayerNorm，似乎想表达只有替换后才能支持Causal Cache。但是在我的理解中，GroupNorm和LayerNorm都作用在通道维度，似乎和时域上的chunking没有必然的联系，也不会破坏Causal的性质？例如CogVideoX的Norm方法使用的是GroupNorm，但是应该也实现了Causal Cache。
    所以这里有些困惑，希望知道你们的想法。

**Comment by qqingzheng** [comment]
你好，非常感谢你的关注。在Pytorch的实现里GroupNorm似乎是在channel维度分组，然后在THW上做normalization。但是在Causal Cache的时候，我们希望THW每一个向量都是独立的做normalization，这样才能做到无损的分块。

![image](https://github.com/user-attachments/assets/51832685-4ad1-49ef-b0f8-c9214bff0d79)

![image](https://github.com/user-attachments/assets/b6b0c753-0be8-445f-b897-e377184bd4f7)


以上是测试结果。如果有什么问题欢迎一起讨论！

**Comment by Chester-CS** [comment]
感谢你的回复，想请教一下你们，是不是觉得CogVideoX中使用的GroupNorm方法实际上有问题？没有办法保持编解码时绝对的Causal特性？

因为diffusers库中和CogVideoX Norm相关的代码似乎确实作用在（C/G，T，H，W）维度：
`self.norm_out = nn.GroupNorm(norm_num_groups, block_out_channels[-1], eps=1e-6)`
`hidden_states = self.norm_out(hidden_states)`

【CogVideoX】[https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/autoencoders/autoencoder_kl_cogvideox.py](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/autoencoders/autoencoder_kl_cogvideox.py)

**Comment by qqingzheng** [comment]
是的，如果CogVideoX的norm采用groupnorm，那无法实现绝对无损的分块推理。
