### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [PKU-YuanGroup/Open-Sora-Plan#7]
Hi,
Thank you for releasing this, I noticed you mentioned that this is an “open source” project but the license is NC which doesn’t classify as an open source license. Is there any chance of could be changed or does the technology this repo depends on also have that license?
Thanks!

**Comment by bhack** [comment]
Also cause there are other efforts under apache license so it could be nice eventually to exchange the cocde
https://github.com/mini-sora/minisora

**Comment by jaretburkett** [comment]
If it is not one of these licenses, it is not **open source** https://opensource.org/license .

**Comment by bhack** [comment]
> If it is not one of these licenses, it is not **open source** https://opensource.org/license . 

For pure code it is true but more in general it is still in WIP:
https://opensource.org/deepdive

**Comment by Colinw2292** [comment]
This is worse than openai.. at least they are transparent that they are closed source, these guys are asking for open source help and in fact are closed sourced.

**Comment by fakerybakery** [comment]
cc @LinB203

**Comment by xnmt9** [comment]
Agreed. You can't pretend to take the moral high ground on Open AI, and then do put your own license restrictions.

This is not an open source project as of now.

**Comment by fakerybakery** [comment]
Personally, I do think open access is better than closed-source with no way for the public to use it but it would be nice to not label it as open source if it’s not licensed under a compliant license

**Comment by ninjasaid2k** [comment]
https://github.com/hpcaitech/Open-Sora - version with apache license.

**Comment by LinB203** [comment]
Change to MIT.

**Comment by fakerybakery** [comment]
Does this code still use the official DiT implementation which is NC-licensed?

**Comment by kabachuha** [comment]
The code is switching away from DiT

**Comment by fakerybakery** [comment]
Thanks for changing it @kabachuha! Unfortunately there's still
> The service is a research preview intended for non-commercial use only. See [LICENSE](https://github.com/PKU-YuanGroup/Open-Sora-Plan/blob/main/LICENSE) for details.
in the README, would you mind removing it?
Thanks!

**Comment by fakerybakery** [comment]
cc @LinB203

**Comment by LinB203** [comment]
It is still in the research stage.

**Comment by xnmt9** [comment]
> It is still in the research stage.

He was referring to the fact that the README still says it's non-commercial, even though the license is permissive.

**Comment by LinB203** [comment]
Fixed.
